language: java
sudo: false
script:
 - mvn clean compile assembly:single
 - cd target
 - mkdir osd-font-converter-preview
 - java -jar ./osd-font-converter-jar-with-dependencies.jar -l=INFO -a -d -u=./osd-font-converter-preview
 - ls -la osd-font-converter-preview
 - zip -r osd-font-converter-preview.zip osd-font-converter-preview
